### ISSUE TITLE
MRZ scanning Part not Working for me  

### ISSUE THREAD

**Issue by LesbatHaithem** [zamirszn/flutter_passport_id_nfc_reader#1]
Hello , i came from the dmrtd liberary link , i found out there that you managed to display the image but i'm stuck in Mrz scanning didn't had the chance to try it , can you tell me please why is that the mrz is not scanning for me ?

**Comment by zamirszn** [comment]
> Hello , i came from the dmrtd liberary link , i found out there that you managed to display the image but i'm stuck in Mrz scanning didn't had the chance to try it , can you tell me please why is that the mrz is not scanning for me ?

hello , the mrz scan uses a fork of mrz_scanner plugin which i modified to work for me , you can try the original mrz_scanner  plugin (it didn't work for my document, doesnt support 3 lines mrz) , i found a fork  https://github.com/NikolaCvetanovic1992/mrz_scanner that added support for 3 line, it works but it doesnt scan my documents so i made some modifications , there's also a new plugin you can try https://github.com/abdullahkaracabey/dmrtd-plugin

**Comment by LesbatHaithem** [comment]
Hello , i changed the MRZ parsing logic  and it works , Thank you so much
